// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-bL615JsyM2QsPpbXhLvy5G9JkAp7Zks',
    appId: '1:998372468797:web:7a37bc0a9f4a57e0bda254',
    messagingSenderId: '998372468797',
    projectId: 'dishdash-3136e',
    authDomain: 'dishdash-3136e.firebaseapp.com',
    storageBucket: 'dishdash-3136e.firebasestorage.app',
    measurementId: 'G-QGZJB0CP9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtVtg8jkkJCHE0wdnA3PsbOBUejZd3ONI',
    appId: '1:998372468797:android:4f4fa578a0da6e1ebda254',
    messagingSenderId: '998372468797',
    projectId: 'dishdash-3136e',
    storageBucket: 'dishdash-3136e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFHjtYVe234qpst8jgHFO-ILKat-0boY',
    appId: '1:998372468797:ios:e9a428bdc173ae94bda254',
    messagingSenderId: '998372468797',
    projectId: 'dishdash-3136e',
    storageBucket: 'dishdash-3136e.firebasestorage.app',
    iosBundleId: 'com.example.dishDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFHjtYVe234qpst8jgHFO-ILKat-0boY',
    appId: '1:998372468797:ios:e9a428bdc173ae94bda254',
    messagingSenderId: '998372468797',
    projectId: 'dishdash-3136e',
    storageBucket: 'dishdash-3136e.firebasestorage.app',
    iosBundleId: 'com.example.dishDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-bL615JsyM2QsPpbXhLvy5G9JkAp7Zks',
    appId: '1:998372468797:web:dc90f935138fa831bda254',
    messagingSenderId: '998372468797',
    projectId: 'dishdash-3136e',
    authDomain: 'dishdash-3136e.firebaseapp.com',
    storageBucket: 'dishdash-3136e.firebasestorage.app',
    measurementId: 'G-MZJZC3VSLV',
  );

}