import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'screens/welcome_screen.dart';
import 'screens/signin_screen.dart';
import 'screens/signup_choice_screen.dart';
import 'screens/register_user_screen.dart';
import 'screens/register_company_screen.dart';
import 'screens/guest_view_screen.dart';
import 'screens/user/user_dashboard_screen.dart';
import 'screens/company/company_dashboard_screen.dart';
import 'screens/company/edit_company_info_screen.dart';
import 'screens/company/post_offer_screen.dart';
import 'screens/company/my_posts_screen.dart';
import 'screens/company/menu_screen.dart';

import 'firebase_options.dart'; // Generated by flutterfire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  Future<Widget> _getInitialScreen() async {
    User? user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      return const WelcomeScreen();
    }

    final uid = user.uid;

    final userDoc = await FirebaseFirestore.instance
        .collection('users')
        .doc(uid)
        .get();
    if (userDoc.exists) {
      return const UserDashboardScreen();
    }

    final companyDoc = await FirebaseFirestore.instance
        .collection('companies')
        .doc(uid)
        .get();
    if (companyDoc.exists) {
      final data = companyDoc.data() as Map<String, dynamic>;
      final companyName = data['name'] ?? 'Company';
      return CompanyDashboardScreen(companyName: companyName);
    }

    return const WelcomeScreen();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DishDash',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.deepOrange),
      routes: {
        '/signin': (context) => const SigninScreen(),
        '/signupchoice': (context) => const SignupChoiceScreen(),
        '/registeruser': (context) => const RegisterUserScreen(),
        '/registercompany': (context) => const RegisterCompanyScreen(),
        '/guest': (context) => const GuestViewScreen(),
        '/userdashboard': (context) => const UserDashboardScreen(),
        '/guest': (context) => const GuestViewScreen(),
        '/editcompanyinfo': (context) => const EditCompanyInfoScreen(),
        '/postoffer': (context) => const PostOfferScreen(),
        '/myposts': (context) => const MyPostsScreen(),
        '/menu': (context) => const MenuScreen(),
      },
      home: FutureBuilder<Widget>(
        future: _getInitialScreen(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          return snapshot.data!;
        },
      ),
    );
  }
}
